name: node-action-test

on:
  workflow_dispatch:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
jobs:
  node-action-test:
    runs-on: shs-act-intel
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm test
