name: node-action-test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
jobs:
  node-action-test:
    runs-on: ubuntu-22-ppc64le
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
      - run: |
          npm --version
          node -v
