name: node-action-test

on:
  workflow_dispatch:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
jobs:
  node-action-test:
    runs-on: shs-act-intel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm --version
          node -v
